kind: Cluster
metadata:
  labels:
    env: dev
    type: eks-workloads
  name: eks-gitops-cluster2
  project: david-clark-demo-project
spec:
  type: eks
  blueprint: default
  cloudprovider: hardik-eks-role
  cloudCredentials: david-clark-aws-key
---
apiVersion: rafay.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-gitops-cluster2
  region: us-west-2
  version: "1.31"
  tags:
    demo: "true"
nodeGroups:
  - name: nodegroup-1
    instanceType: t3.xlarge
    desiredCapacity: 2
    volumeType: gp3
    volumeSize: 50
    privateNetworking: true
    volumeEncrypted: true
    volumeKmsKeyID: f12c2166-21dc-418f-881a-f95c28dbce22
    #amiFamily: Ubuntu2004
    iam:
      #withAddonPolicies:
        # albIngress: true
        # autoScaler: true
        # imageBuilder: true
        # efs: true